config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get '/search' => 'search#index'
    get '/search/adoptions' => 'search#adoptions'
  end
  
  resources :animals do
  	resources :images
  end
  
  resources :animals do
  	resources :events
  end

  resources :animals do
    resources :adoptions
  end

  resources :comments

  devise_for :users, controllers: { registrations: "registrations" }

  get '/search' =>'search#search'

  root 'welcome#index'

  get '/.well-known/acme-challenge/:id' => 'welcome#letsencrypt'
  
end

app/models/adoption.rb
class Adoption < ApplicationRecord
	belongs_to :animal
	has_many :comments
	reverse_geocoded_by :latitude, :longitude
	before_validation :reverse_geocode  # auto-fetch address
	geocoded_by :address
	before_validation :geocode, :if => :address_changed?

	
	def same_region()
		@all_nearbys = self.nearbys(5)
		
		@all_nearbys.select { |a| a.status == "adoption" }
	end

end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  #before_action :set_adoption, only: [:show, :edit, :update, :destroy]

  def index
    @adoptions = Adoption.where(animal_id: params[:animal_id])
  end

  def show
    @animal = Animal.find(params[:animal_id])
    @adoption = Adoption.find(params[:id])    
    @comment = @adoption.comments.new #cria um novo comentário para aquele evento
    @comments = @adoption.comments
  end

  
  def new
    @animal = Animal.find(params[:animal_id])
    @adoption = Adoption.new(animal: @animal)
  end

  
  def edit
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @adoption = Adoption.new(adoption_params)
    @adoption.animal = @animal

    respond_to do |format|
      if @adoption.save
        format.html { redirect_to :controller => 'search', :action => 'search',  notice: 'Adoção criada com sucesso' }
        format.json { render :show, status: :created, location: @adoption }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @adoption.update(adoption_params)
        format.html { redirect_to animal_events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @adoption }
      else
        format.html { render :edit }
        format.json { render json: @adoption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @adoption.destroy
    respond_to do |format|
      format.html { redirect_to animal_events_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def adoption_params
      params.require(:adoption).permit(:date_adoption, :comment, :latitude, :longitude, :address, :vaccinated)
    end
end

app/views/adoptions/_comments.html.erb
<% @comments.each do |comment| %>
	<% next if !comment.persisted? %>
	<div class="comments">
		<p>Autor: <%= comment.user.name %> </p>
		<br>
		<p>Comentario: <%= comment.body %></p>

	</div>
<% end %>

app/views/adoptions/_form.html.erb
<%= form_for([animal, @adoption]) do |f| %>
    <% if @adoption.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>
            <ul>
            <% @adoption.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    <div class="select-images">
        <a href="javascript:void(0)" class="link-md" id="exist" onclick="hideMapa();toggleCreation();">Digitar um endereço manualmente</a>
        <div id="exist-container" class="hidden">
            <a href="javascript:void(0)" class="link-md hidden" id="newItem" onclick="toggleCreation();showMapa()">Usar localização atual</a>
            <div class="field" data-toggle="tooltip"> 
                <div class="field">
                    <%= f.label :address, "Endereço" %>
                    <button type="button" class="btn btn-tooltip" data-container="body" data-toggle="popover" data-placement="right" data-content="Exemplo de formato de endereço:  Av. Comendador Aladino Selmi, 10, Campinas, SP ">
                    ?  
                    </button>
                    <%= f.text_field :address, class: "form-control", placeholder: 'Av. Comendador Aladino Selmi, 10, Campinas, SP' %>
                </div>
            </div>
        </div>
    </div>
    <div id="new">
        <div id="map-canvas"></div>
    </div>
    <div class="field">
        <%= f.label :date_adoption, "Data do evento" %>
        <%= f.text_field :date_adoption, class: "form-control",placeholder: 'xx/xx/xxxx' %>
    </div>


    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>

    <div class="field">
        <%= f.label :comment, "Detalhes do adoção" %>
        <%= f.text_area :comment, class: "form-control" %>
    </div>

    <div class="field">
        <%= f.label :vaccinated, "É vacinado?" %>
        <%= f.check_box :vaccinated %>
    </div>

    <div class="actions"%>
        <%= f.submit "Enviar", class: "btn-secundario" %>
    </div>
<% end %>

app/views/adoptions/_form_comment.html.erb
<%= form_for(@comment) do |f| %>
    
    <%= f.hidden_field :adoption_id %>
    <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>" >

    <div class="field">
        <%= f.label :body, "Digite seu comentário" %>
        <%= f.text_area :body, :maxlength => 240, class: "form-control" %>
    </div>

    <div class="actions"%>
        <%= f.submit "Enviar", class: "btn-secundario" %>
    </div>
    
<% end %>

app/views/adoptions/_show_animal.html.erb
<div class="col-md-3 col-sm-12 col-xs-12 box-infos">
    <h3>Dados do animal</h3>
    <div>
        <h4>Tipo: </h4>
        <p><%= @animal.animal_type %></p>
    </div>
    <div>
        <h4>Raça: </h4>
        <% if  @animal.race_dog_id %>
            <p><%= @animal.race_dog.name %></p>
        <% elsif @animal.race_cat_id %>
            <p><%= @animal.race_cat.name %></p>
        <% end %>
    </div>
    <div>
        <h4>Cor: </h4>
        <p><%= @animal.color %></p>
    </div>
    <div>
        <h4>Gênero: </h4>
        <p><%= @animal.sex %></p>
    </div>
    <div>
        <h4>Idade: </h4>
        <p><%= @animal.age %></p>
    </div>
    <div>
        <h4>Porte: </h4>
        <p><%= @animal.size %></p>
    </div>
    <h3>Dados da adoção</h3>
    <div>
        <div>
            <h4>Data: </h4>
            <p><%= @adoption.date_adoption %></p>
        </div>
        <div>
            <h4>Comentário: </h4>
            <p><%= @adoption.comment %></p>
        </div>
        <div>
            <h4>Vacinado: </h4>
            <p><%= @adoption.vaccinated ? 'Sim' : 'Não' %></p>
        </div>
        <input type="hidden" name="latitude" id="lat" value="<%= @adoption.latitude %>">
        <input type="hidden" name="longitude" id="long" value="<%= @adoption.longitude %>">
</div>

app/views/adoptions/index.html.erb
<%= render :partial => 'layouts/header' %>
<main>
   <section class="new-animal">
    <div class="container">
      <table>
        <thead>
          <tr>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @adoptions.each do |adoption| %>
            <tr>
              <td><p><%= adoption.comment %>></p></td>
              <td><%= link_to 'Show', animal_adoption_path(params[:animal_id], adoption) %></td>
              <td><%= link_to 'Edit', edit_animal_adoption_path(params[:animal_id], adoption) %></td>
              <td><%= link_to 'Destroy', animal_adoption_path(params[:animal_id], adoption), method: :delete, data: { confirm: 'Are you sure?' } %></td>

            </tr>
          <% end %>
        </tbody>
      </table>
      
    </div> 
  </section>
</main>
<%= render :partial => 'layouts/footer' %>

app/views/adoptions/new.html.erb
<%= render :partial => 'layouts/header' %>
<main>
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-centered">
				<section class="steps-cadastro">
					<div class="alert alert-success alert-dismissible" role="alert">
					    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					    <p id="notice"><%= notice %></p>
					</div>
				    <section class="steps-cadastro">
					      <ol class="row">
					        <li class="col col-md-3  col-sm-3 col-xs-3">Dados do animal</li>
					        <li class="col col-md-3 col-sm-3 col-xs-3">Imagens do animal</li>
					        <li class="col col-md-3 col-sm-3 col-xs-3">Endereço</li>
					        <li class="col col-md-3 col-sm-3 col-xs-3">Pronto!</li>
					      </ol>
					      <div class="progress">
					        <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;">
					          75% Completos
					        </div>
					      </div>
				    </section>
				</section>
				<section class="new-event">
			    	<div class="form-container">
						<h2>Mais informações</h2>
						<p>Aqui você indica qual é o endereço que o animal está para ser doado, a data e pode escrever alguma descrição e se o animal é vacinado.</p>
						<%= render 'form', animal: @animal, adopt: @adoption %>
					</div> 
				</section>
			</div>
		</div>
	</div>
</main>
<%= render :partial => 'layouts/footer' %>

app/views/adoptions/show.html.erb
<%= render :partial => 'layouts/header' %>
<main>
    <section class="show-animal">
        <div class="container">
            <h1><%= @animal.name %> - Adoção</h1>            
            <div class="share-buttons">
                <a class="twitter-share-button"
                href="https://twitter.com/intent/tweet?text=Animal para adoção:%20<%= @animal.name %>.%20Local:%20<%= @adoption.address %> "
                data-size="small">
                Tweet</a>
                <div class="fb-share-button" data-href="http://resgatabichos.herokuapp.com/animals/<%= @animal.id %>/adotoptions/<%= @adoption.id %>" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=Animal para adoção:%20<%= @animal.name %>.%20Local:%20<%= @adoption.address %> ">Share</a></div>
            </div>
            <p>Adicionado por: <%= @animal.user.name %></p>
            <div class="show-animal-container">         
                <div class="row">
                    <%= render 'show_animal', animal: @animal %>
                </div>
                <div class="col-md-5 col-sm-12 col-xs-12 box-img">
                    <h3>Localização</h3>
                    <div id="mapholder"></div>
                    <h3>Imagem</h3>
                    <ul>
                        <% @animal.images.each do |image| %>
                            <li><img class="img-responsive" src="<%= image.image.url %>"></li>
                        <% end %>
                    </ul>
                </div>
                
                <div class="col-md-4 col-sm-12 col-xs-12">
                    <h3>Comentários</h3>

                    <%= render :partial => 'comments' %>

                    <% if current_user.blank? %>
                        <p>Para comentar você precisa estar logado!</p>
                    <% end %>
                    <% unless current_user.blank? %>        
                        <%= render :partial => 'form_comment' %>
                    <% end %>
                    
                </div>
            </div>
            <div class="separator"></div>
            <% unless current_user.blank? %>
                <% if (@animal.user_id == current_user.id) %>
                    <%= link_to 'Editar', edit_animal_path(@animal) %> |
                <% end %>    
            <% end %>
            
        </div>  
    </section>
</main>
<%= render :partial => 'layouts/footer' %>
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10&appId=425320334277338';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>