config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get '/search' => 'search#index'
    get '/search/adoptions' => 'search#adoptions'
  end
  
  resources :animals do
  	resources :images
  end
  
  resources :animals do
  	resources :events
  end

  resources :animals do
    resources :adoptions
  end

  resources :comments

  devise_for :users, controllers: { registrations: "registrations" }

  get '/search' =>'search#search'

  root 'welcome#index'

  get '/.well-known/acme-challenge/:id' => 'welcome#letsencrypt'
  
end

app/models/animal.rb
class Animal < ApplicationRecord
	belongs_to :user
	has_many :images, dependent: :destroy
	has_many :events, dependent: :destroy
	has_many :adoptions, dependent: :destroy
	belongs_to :race_cat, optional: true
	belongs_to :race_dog, optional: true
	validates :name, presence: true
	validates :color, presence: true
	validates :sex, presence: true
	validates :age, presence: true
	validates :size, presence: true
	validates :animal_type, presence: true

	def self.search(search)
		scope = self

		if search[:state].present? || search[:data_event].present? || search[:status].present?
			scope = scope.joins(:events) 
		end
		scope = scope.where("events.address LIKE ?", "% #{search[:state].upcase}%") if search[:state].present?
		scope = scope.where(events: { data_event: search[:data_event] }) if search[:data_event].present?

		scope = scope.where(animal_type: search[:animal_type]) if search[:animal_type].present?
		scope = scope.where(sex: search[:sex]) if search[:sex].present?
		scope = scope.where(size: search[:size]) if search[:size].present?
		scope = scope.where(color: search[:color]) if search[:color].present?
		scope = scope.where(events: { status: search[:status] }) if search[:status].present?

		scope
	end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    before_action :set_animal, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:show]
    before_filter :require_permission, only: [:edit, :destroy]

    # GET /animals
    # GET /animals.json
    def index
        @animals = current_user.animals.all
        
    end

    # GET /animals/1
    # GET /animals/1.json
    def show
    end

    # GET /animals/new
    def new
        @dog_races = dog_races
        @cat_races = cat_races
        @ages = ages
        @animals = current_user.animals.all
        @animal = current_user.animals.new
        @status_animal = params[:status]
        
    end

    # GET /animals/1/edit
    def edit
        @dog_races = dog_races
        @cat_races = cat_races
        @ages = ages
        @animals = current_user.animals.all
    end

    # POST /animals
    # POST /animals.json
    def create
        @animals = current_user.animals.all
        @animal = current_user.animals.new(animal_params)
        @user = current_user
        
        respond_to do |format|
            if @animal.save

                format.html { redirect_to new_animal_image_path(@animal, { status: params[:status] }), notice: 'Animal criado com sucesso' }
                format.json { render :show, status: :created, location: @animal }
            else
                @dog_races = dog_races
                @cat_races = cat_races
                @ages = ages
                format.html { render :new }
                format.json { render json: @animal.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /animals/1
    # PATCH/PUT /animals/1.json
    def update
        respond_to do |format|
            if @animal.update(animal_params)
                format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
                format.json { render :show, status: :ok, location: @animal }
            else
                format.html { render :edit }
                format.json { render json: @animal.errors, status: :unprocessable_entity }
          end
        end
    end

    # DELETE /animals/1
    # DELETE /animals/1.json
    def destroy
        @animal.destroy
        respond_to do |format|
            format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
        @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
        params.require(:animal).permit(:name, :race_dog_id, :race_cat_id, :color, :animal_type, :sex, :age, :size)
    end

    def require_permission
      if current_user != Animal.find(params[:id]).user
        redirect_to root_path
      end
    end

    def dog_races
      RaceDog.all.map { |race| [ race.name, race.id ] }
    end

    def cat_races
      RaceCat.all.map { |race| [ race.name, race.id ] }
    end

    def ages
    [
      ['Até 1 ano', 'Até 1 ano'],
      ['1', '1'],
      ['2','2'],
      ['3','3'],
      ['4','4'],
      ['5','5'],
      ['6','6'],
      ['7','7'],
      ['8','8'],
      ['9','9'],
      ['10','10'],
      ['11','11'],
      ['12','12'],
      ['13','13'],
      ['14','14'],
      ['15','15'],
      ['16','16'],
      ['17','17'],
      ['18','18'],
      ['19','19'],
      ['Mais que 20','Mais que 20']
    ]
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for(animal) do |f|  %>
  <% if animal.errors.any? %>
	<div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>
	  <ul>
	  <% animal.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	  <% end %>
	  </ul>
	</div>
  <% end %>
  <% if @animals.any? && @animal.new_record? %>
	  <a href="javascript:void(0)" class="link-md link-color" id="exist" onclick="toggleCreation();">Usar um animal já cadastrado</a>
	  <div id="exist-container" class="hidden">
	  	<a href="javascript:void(0)" class="link-md hidden link-color" id="newItem" onclick="toggleCreation();">Criar novo animal</a>
		  <div class="field" data-toggle="tooltip"> 
		  	<label>Animais já cadastrados</label>
		  	<select class="form-control" id="cadastrados">
		  		<option value=""></option>
		  		<% @animals.each do |animal| %>
		  		<option value="<%=animal.id %>"><%= animal.name %></option>
		  		<% end %>
		  	</select>
		  </div>
		  <div class="actions">
		  	<a href="" class="btn-secundario btn-fake hidden" id="next">
					Próximo passo
					<span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
				</a>
		  </div>
	  </div>
  <% end %>
  <div id="new">
  	<div class="field" data-toggle="tooltip">
			<%= f.label :name, "Nome" %>
			<%= f.text_field :name, class: "form-control" %>
	</div>

	  <div class="field" data-toggle="tooltip">
			<%= f.label :animal_type, "Tipo" %>
			<%= f.select(:animal_type, [['Cão', 'Cão'], ['Gato', 'Gato']], {}, { class: 'form-control' }) %>
	  </div>

	  <div class="field" data-toggle="tooltip" id="dogs-list">
			<%= f.label :race_dog_id, "Raça" %>
			<%= f.select(:race_dog_id, options_for_select(@dog_races) , {}, { class: 'form-control', :id => "dogs-lists" }) %>
	  </div>

	  <div class="field hidden" data-toggle="tooltip" id="cats-list">
			<%= f.label :race_cat_id, "Raça" %>
			<%= f.select(:race_cat_id, options_for_select(@cat_races) , {}, { class: 'form-control', :id => "cats-lists" }) %>
	  </div>

	  <div class="field" data-toggle="tooltip">
			<%= f.label :color, "Cor" %>
			<%= f.text_field :color, class: "form-control" %>
	  </div>

	  <div class="field" data-toggle="tooltip">
			<%= f.label :sex, "Sexo" %>
			<%= f.select(:sex, [['Macho', 'Macho'], ['Fêmea', 'Fêmea']], {}, { class: 'form-control'}) %>
	  </div>

	  <div class="field" data-toggle="tooltip">
			<%= f.label :age, "Idade" %>
			<%= f.select(:age, options_for_select(@ages) , {}, { class: 'form-control', :id => "ages" }) %>
	  </div>

	  <div class="field" data-toggle="tooltip">
			<%= f.label :size, "Porte" %>
			<%= f.select(:size, [['Pequeno', 'Pequeno'], ['Médio', 'Médio'], ['Grande', 'Grande']], {}, { class: 'form-control'}) %>
	  </div>

	  <input type="hidden" id="status_animal" name="status" value="<%= @status_animal %>">	  

	  <div class="actions">
		<%= f.submit "Próximo passo", class: "btn-secundario" %>
	  </div>
  </div>
<% end %>

app/views/animals/edit.html.erb
<%= render :partial => 'layouts/header' %>

<main>
  <section class="edit-animal">
    <div class="container">
    
		<h1>Editar Animal</h1>

		<%= render 'form', animal: @animal %>

		<%= link_to 'Show', @animal %> |
		<%= link_to 'Back', animals_path %>
    </div>
  </section>
</main>
<%= render :partial => 'layouts/footer' %>

app/views/animals/index.html.erb
<%= render :partial => 'layouts/header' %>

<main>
  <section class="index-animals">
    <div class="container">
      
      <div id="error_explanation" class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p id="notice"><%= notice %></p>
      </div>
      <div class="row">
        <div class="col-md-9">
          <h1>Meus animais</h1>  
        </div>
        <div class="col-md-3">
          <%= link_to 'Cadastrar novo animal', new_animal_path, class: "btn-secundario" %>
        </div>
      </div>
      <div class="row">
        <% @animals.each do |animal| %>
          <div class="col-md-3 col-sm-6 col-xs-12">
            <div class="card-animals-container">
              <ul>
                <% animal.images.take(1).each do |image, i| %>
                  <li>
                    <img class="img-responsive" src="<%= image.image.url %>" class="img-rounded">
                  </li>
               <% end %>
              </ul>
              <p>Nome: <%= animal.name %></p>
              <p>Gênero: <%= animal.sex %></p>
              <p>Idade: <%= animal.age %></p>
              <div class="row">
                <div class="col-md-4 col-sm-4 col-xs-4 links">
                  <%= link_to 'Deletar', animal, method: :delete, data: { confirm: 'Você tem certeza? Ao deletar um animal você irá excluir suas fotos e os eventos cadastrados.' } %>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-4 links">
                  <%= link_to 'Editar', edit_animal_path(animal) %>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-4 links">
                  <%= link_to 'Exibir', animal %>
                  <!-- listagem de animais -> animal ->listagem de imagens e de eventos... -->

                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>  
  </section>
</main>
<%= render :partial => 'layouts/footer' %>

app/views/animals/new.html.erb
<%= render :partial => 'layouts/header' %>

<main>
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-centered">
				<section class="steps-cadastro text-center">	
					<ol class="row">
						<li class="col col-md-3 col-sm-3 col-xs-3">Dados do animal</li>
						<li class="col col-md-3 col-sm-3 col-xs-3">Imagens do animal</li>
						<li class="col col-md-3 col-sm-3 col-xs-3">Local do evento</li>
						<li class="col col-md-3 col-sm-3 col-xs-3">Pronto!</li>
					</ol>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;">
					    25% Completos
					  </div>
					</div>
				</section>
				 <section class="new-animal">
				    
			    	<div class="form-container" id="form-animal">
						<h2>Novo animal</h2>
						<p>Insira as informações do animal e tudo bem se não tiver todas as informações, pode colocar aproximadamente.</p>

						<%= render 'form', animal: @animal %>

					</div>
				      
				</section>
			</div>
		</div>
	</div>
</main>
<%= render :partial => 'layouts/footer' %>

app/views/animals/show.html.erb
<%= render :partial => 'layouts/header' %>
<div class="row">
     <div class="col-md-8 col-centered">
        <div class="col-md-3 col-sm-12 col-xs-12 box-infos">
            <h3>Dados do animal</h3>
            <div>
                <h4>Tipo: </h4>
                <p><%= @animal.animal_type %></p>
            </div>
            <div>
                <h4>Raça: </h4>
                <% if  @animal.race_dog_id %>
                    <p><%= @animal.race_dog.name %></p>
                <% elsif @animal.race_cat_id %>
                    <p><%= @animal.race_cat.name %></p>
                <% end %>
            </div>
            <div>
                <h4>Cor: </h4>
                <p><%= @animal.color %></p>
            </div>
            <div>
                <h4>Gênero: </h4>
                <p><%= @animal.sex %></p>
            </div>
            <div>
                <h4>Idade: </h4>
                <p><%= @animal.age %></p>
            </div>
            <div>
                <h4>Porte: </h4>
                <p><%= @animal.size %></p>
            </div>
        </div>
    </div>   
</div>

<%= render :partial => 'layouts/footer' %>