config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get '/search' => 'search#index'
    get '/search/adoptions' => 'search#adoptions'
  end
  
  resources :animals do
  	resources :images
  end
  
  resources :animals do
  	resources :events
  end

  resources :animals do
    resources :adoptions
  end

  resources :comments

  devise_for :users, controllers: { registrations: "registrations" }

  get '/search' =>'search#search'

  root 'welcome#index'

  get '/.well-known/acme-challenge/:id' => 'welcome#letsencrypt'
  
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :animal
	has_attached_file :image,
					  :storage => :s3,
					  :s3_region => "us-west-1",
					  :bucket => "resgataimgs",
					  :s3_host_name => "s3-us-west-1.amazonaws.com", 
					  :s3_credentials => {  :access_key_id  => ENV['AWS_KEY'],
											:secret_access_key => ENV['AWS_SECRET']
										}
	validates_attachment :image,
  					  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }, presence: true
  	validates_attachment_size :image, :in => 0.megabytes..10.megabytes
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.where(animal_id: params[:animal_id])
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @animal = Animal.find(params[:animal_id])
    @images = @animal.images
  end

  # GET /images/new
  def new
    @animal = Animal.find(params[:animal_id])
    @animal_images = @animal.images
  
    @image = Image.new(animal: @animal)
  end

  # GET /images/1/edit
  def edit
    @animal_images = @animal.images
  end

  # POST /images
  # POST /images.json
  def create
    @animal = Animal.find(params[:animal_id])
    @image = @animal.images.new(image_params)
    respond_to do |format|
      if @image.save
        if params[:status] == "adoption"
          flash.now[:notice] = 'Imagem criada com sucesso'
          format.html { redirect_to new_animal_adoption_path(@animal, { status: params[:status] }) }
          format.json { render :show, status: :created, location: @image }
        else
          format.html { redirect_to new_animal_event_path(@animal, { status: params[:status] }), notice: 'Imagem criada com sucesso' }
          format.json { render :show, status: :created, location: @image }
        end
      else
        @animal = Animal.find(params[:animal_id])
        @animal_images = @animal.images
        @image = Image.new(animal: @animal)
        flash[:notice] = "Por gentileza, sua imagem precisa ser menor que 10mb"
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to animal_image_path, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to animal_images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @animal = Animal.find(params[:animal_id])
    @image = @animal.images.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def image_params
    params.fetch(:image, {}).permit(:image)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for([animal, image]) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>
      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if animal.images.any? %>
    <div class="select-images">
      <a href="javascript:void(0)" class="link-md link-color" id="exist" onclick="toggleCreation();">Usar uma imagem já cadastrada</a>
      <div id="exist-container" class="hidden">
        <a href="javascript:void(0)" class="link-md hidden link-color" id="newItem" onclick="toggleCreation();">Criar nova imagem</a>
        <div class="field" data-toggle="tooltip"> 
          <label>Imagens já cadastradas</label>
          <select class="form-control" id="cadastrados">
            <option value=""></option>
            <% @animal_images.each do |image| %>
            <option value="<%= image.animal.id %>"><%= image.image_file_name %></option>
            <% end %>
          </select>
        </div>
        <div class="actions">
          <a href="" class="btn-secundario btn-fake hidden" id="next">
            Próximo passo
            <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
          </a>
        </div>
      </div>
    </div>
  <% end %>
  <div id="new">
    <div class="field" data-toggle="tooltip">
      <%= f.file_field :image, value: "Escolher imagem", class: "form-control"  %>   
    </div>
    <%= hidden_field_tag :status, params[:status] %>
    <div class="actions">   
      <%= f.submit "Próximo passo", class: "btn-secundario"  %>
    </div>
  </div>
<% end %>

app/views/images/edit.html.erb
<%= render :partial => 'layouts/header' %>

<main>
  <section class="edit-animal">
    <div class="container">
		<h1>Editing Image</h1>

		<%= render 'form', animal: @animal, image: @image %>

		<%= link_to 'Show', @image %> |
		<%= link_to 'Back', animal_images_path %>
    </div>  
  </section>
</main>
<%= render :partial => 'layouts/footer' %>

app/views/images/index.html.erb
<%= render :partial => 'layouts/header' %>
<main>
   <section class="new-animal">
    <div class="container">
      <table>
        <thead>
          <tr>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @images.each do |image| %>
            <tr>
              <td><img src="<%= image.image.url %>"></img></td>
              <td><%= link_to 'Show', animal_image_path(params[:animal_id], image) %></td>
              <td><%= link_to 'Edit', edit_animal_image_path(params[:animal_id], image) %></td>
              <td><%= link_to 'Destroy', animal_image_path(params[:animal_id], image), method: :delete, data: { confirm: 'Are you sure?' } %></td>

            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Nova imagem ', new_animal_image_path(params[:animal_id]) %>
    </div> 
  </section>
</main>
<%= render :partial => 'layouts/footer' %>

app/views/images/new.html.erb
<%= render :partial => 'layouts/header' %>
<main>
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-centered">
				<div class="alert alert-success alert-dismissible" role="alert">
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				    <p id="notice"><%= notice %></p>
				</div>
			    <section class="steps-cadastro">
				      <ol class="row">
				        <li class="col col-md-3 col-sm-3 col-xs-3">Dados do animal</li>
				        <li class="col col-md-3 col-sm-3 col-xs-3">Imagens do animal</li>
				        <li class="col col-md-3 col-sm-3 col-xs-3">Local do evento</li>
				        <li class="col col-md-3 col-sm-3 col-xs-3">Pronto!</li>
				      </ol>
				      <div class="progress">
				        <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
				          50% Completos
				        </div>
				      </div>
			    </section>
			    <section class="new-animal">
			    	<div class="form-container" id="form-image">
						<h2>Nova imagem</h2>
						<p>Insira alguma foto do animal. Caso não tenha fotos, procure uma imagem que mais se pareça com o animal.</p>
						
						<%= render 'form', animal: @animal, image: @image %>

						<% if flash[:notice] %>
							<div class="notice"><%= flash[:notice] %></div>
						<% end %>
					</div>
				</section>
			</div>
		</div>
	</div>
</main>
<%= render :partial => 'layouts/footer' %>

app/views/images/show.html.erb
<%= render :partial => 'layouts/header' %>

<main>
  <section class="show-animal">
    <div class="container">
			<p id="notice"><%= notice %></p>


			<img src="<%= @image.image.url %>"></img>
			
			<%= link_to 'Edit', edit_animal_image_path(@animal, @image) %> |
			<%= link_to 'Back', animal_images_path %>
		</div>
	</section>
</main>
<%= render :partial => 'layouts/footer' %>